# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  dockerfile:  # id of input
    description: 'Name of the Dockerfile (default: "github.workspace/Dockerfile")'
    required: true
    default: ${{ github.workspace }}    
outputs:
  dockerfile: # id of output
    description: 'xxxxxxxxxxxxxxxxxx'
runs:
  using: 'docker'
  image: ${{ inputs.dockerfile }}
  args:
    - ${{ inputs.dockerfile }}
